# Generated by Django 3.2 on 2021-04-28 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='name_accessories')),
                ('price', models.FloatField(verbose_name='price')),
                ('rating', models.FloatField(verbose_name='rating')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('image', models.CharField(max_length=300, verbose_name='image')),
                ('url', models.CharField(max_length=300, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Accessory',
                'verbose_name_plural': 'Accessories',
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='name_laptops')),
                ('price', models.FloatField(verbose_name='price')),
                ('rating', models.FloatField(verbose_name='rating')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('image', models.CharField(max_length=300, verbose_name='image')),
                ('url', models.CharField(max_length=300, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='name_phones')),
                ('price', models.FloatField(verbose_name='price')),
                ('rating', models.FloatField(verbose_name='rating')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('image', models.CharField(max_length=300, verbose_name='image')),
                ('url', models.CharField(max_length=300, verbose_name='url')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=300, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='offeredproduct',
            name='company',
            field=models.CharField(max_length=300, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='offeredproduct',
            name='name',
            field=models.CharField(max_length=300, verbose_name='name2'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='phone',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
